---
- name: Fetch and Print EC2 Instance IDs
  hosts: localhost
  gather_facts: false
  vars:
    aws_region: "us-east-1"

  tasks:
    - name: Get EC2 instance information
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "abdallah-ansible"
      register: ec2_info

    - name: Ensure EC2 instances exist
      fail:
        msg: "No EC2 instances found in the specified region: {{ aws_region }}"
      when: ec2_info.instances | length == 0

    - name: Print all instance IDs
      debug:
        msg: "Instance ID: {{ item.instance_id }}"
      loop: "{{ ec2_info.instances }}"
