- hosts: localhost
  gather_facts: False
  roles:
    - ec2

- hosts: all
  become: true
  pre_tasks:
    - name: update repo index
      apt: 
        update_cache: yes
      changed_when: False
  roles:
    - mysql
    - wordpress
    #- grafana
  tags:
    - config
