- hosts: localhost
  gather_facts: False
  roles:
    - ec2
  tags: ec2,setup

- hosts: all
  become: true
  pre_tasks:
    - name: update repo index
      package: 
        update_cache: yes
      changed_when: False
  roles:
    - mysql
    - wordpress
  tags: config
