
- name: Create backup directory
  become: true
  file:
    path: "{{ backup_directory }}"
    state: directory
    mode: '0755'
  tags: mysql

- name: Deploy backup script
  become: true
  template:
    src: backup.sh.j2
    dest: /usr/local/bin/mysql_backup.sh
    mode: '0755'
  tags: mysql

- name: Configure cron job for backups
  become: true
  cron:
    name: "MySQL Backup"
    minute: "{{ cron_time.split()[0] }}"
    hour: "{{ cron_time.split()[1] }}"
    day: "{{ cron_time.split()[2] }}"
    month: "{{ cron_time.split()[3] }}"
    weekday: "{{ cron_time.split()[4] }}"
    job: "/usr/local/bin/mysql_backup.sh"
  tags: mysql
