---
# tasks file for mysql

- name: Install MySQL 8
  become: yes
  apt:
    name: mysql-server
    state: present
  tags: mysql

- name: Ensure MySQL is running
  become: yes
  service:
    name: mysql
    state: started
    enabled: yes
  tags: mysql
  
- name: Install MySQL Python dependencies for Python 3
  become: yes
  package:
    name:
      - python3-pip
      - python3-dev
      - libmysqlclient-dev
      - build-essential
  tags: mysql

- name: Install PyMySQL for Python 3
  become: yes
  pip:
    name: PyMySQL
  tags: mysql

- name: Setup the root user password and access with hosts
  become: yes
  become_user: root
  mysql_user:
    name: "{{ mysql_superuser }}"
    host: "{{ item }}"
    password: "{{ mysql_superuser_password }}"
    login_user: root
    login_password: "{{ mysql_superuser_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
    state: present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  tags: mysql

- name: Create wordpress database
  become: yes
  mysql_db:
    login_user: "{{ mysql_superuser }}"
    login_password: "{{ mysql_superuser_password }}"
    name: "{{ wordpress_database }}"
    state: present
  tags: mysql,wordpress_db

- name: Create wordpress user with privileges
  become: yes
  mysql_user:
    login_user: "{{ mysql_superuser }}"
    login_password: "{{ mysql_superuser_password }}"
    name: "{{ wordpress_user }}"
    password: "{{ wordpress_user_password }}"
    priv: "{{ wordpress_database }}.*:ALL"
    state: present
  tags: mysql,wordpress_db

- include_tasks: cron.yml
