---
# tasks file for ec2
- name: Provision an EC2 instance with a public IP address
  amazon.aws.ec2_instance:
    name: "{{ machine_name }}"
    key_name: "{{ key_name }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    instance_type: "{{ instance_type }}"
    security_group:  "{{ security_group }}"
    network:
      assign_public_ip: true
    image_id: "{{ image_id }}"
    tags:
      env: "{{ env_tag }}"
      task: "{{ task_tag }}"
  register: result

- name: Wait to completely provision instances
  pause:
    minutes: 4

- name: Refresh inventory after creating EC2 instances
  meta: refresh_inventory

- name: Print the URL of the EC2 instance
  debug:
    msg: "EC2 instance URL is http://{{ result.instances[0].public_ip_address }}"